#!/bin/bash

python3 /var/www/chatboto/supportua/populator.py
MYPROG="waitress"
PGREP="/usr/bin/pgrep"
$PGREP ${MYPROG}
if [ $? -ne 0 ]
then
    source "/var/www/chatboto/.pyenv/versions/3.8.5/envs/env/bin/activate"
    nohup waitress-serve --port=5000 app:app
fi
