#!/bin/bash

python3 /var/www/chatboto/supportua/populator.py
MYPROG="mpbot"
PGREP="/usr/bin/pgrep"
$PGREP ${MYPROG}
if [ $? -ne 0 ]
then
    source "/var/www/chatboto/.pyenv/versions/3.8.5/envs/env/bin/activate"
    bash -c "exec -a mpbot python /var/www/chatboto/supportua/app.py &"
fi
